networks:
  caddy:
    external: true
  dns:
    external: true

services:
  caddy:
    container_name: caddy
    environment:
      - CADDY_INGRESS_NETWORKS=caddy
      - CADDY_DOCKER_CADDYFILE_PATH=/etc/caddy/Caddyfile
    hostname: caddy
    image: caddy:latest
    networks:
      - caddy
      - dns
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    restart: unless-stopped
    volumes:
      - ./conf:/etc/caddy
      - ./site:/srv
      - caddy_data:/data

volumes:
  caddy_data:
  caddy_config: