version: "3"
services:
  csit:
    build:
      args:
        "UBUNTU_VERSION": "22.04"
      context: "."
    command: "/bin/bash"
    entrypoint: "/postCreateCommand.sh"
    volumes:
      - "${HOME}/workspace/:/root/workspace/"
      - "${HOME}/.ssh:/root/.ssh"
      - "${HOME}/.aws:/root/.aws"
      - "container-bashhistory:/commandhistory"
volumes:
  container-bashhistory:
