networks:
  traefik:
    external: true
  ollama:
    external: true

volumes:
  anything-llm-data:

services:
  anything-llm:
    image: "mintplexlabs/anythingllm:master"
    container_name: "anything-llm"
    environment:
      - "STORAGE_DIR=/app/server/storage"
    hostname: "anything-llm"
    networks:
      - "caddy"
      - "ollama"
    volumes:
      - "anything-llm-data:/app/server/storage"
