services:
  ollama:
    container_name: "ollama"
    image: "ollama/ollama:latest"
    hostname: "ollama"
    networks:
      - "proxy"
    environment:
      - "PUID=${PUID:-1000}"
      - "PGID=${PGID:-1000}"
      - "OLLAMA_KEEP_ALIVE=24h"
      - "ENABLE_IMAGE_GENERATION=True"
      - "COMFYUI_BASE_URL=http://comfyui:8188"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "./ollama:/root/.ollama"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ollama.entrypoints=https"
      - "traefik.http.routers.ollama.tls=true"
      - "traefik.http.routers.ollama.middlewares=default-headers@file"
      - "traefik.http.routers.ollama.middlewares=ollama-auth"
      - "traefik.http.services.ollama.loadbalancer.server.port=11434"
      - "traefik.http.routers.ollama.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.users=${OLLAMA_API_CREDENTIALS}"
    extends:
      file: "../extends/hwaccel.ml.yml"
      service: "cpu" # set to one of [armnn, cuda, openvino, openvino-wsl]

  open-webui:
    container_name: "open-webui"
    image: "ghcr.io/open-webui/open-webui:latest"
    hostname: "open-webui"
    networks:
      - "proxy"
    restart: "unless-stopped"
    environment:
      - "PUID=${PUID:-1000}"
      - "PGID=${PGID:-1000}"
      - "OLLAMA_BASE_URL=http://ollama:11434"
      - "ENABLE_IMAGE_GENERATION=True"
      - "COMFYUI_BASE_URL=http://comfyui:8188"
      - "ENABLE_RAG_WEB_SEARCH=True"
      - "RAG_WEB_SEARCH_ENGINE=searxng"
      - "RAG_WEB_SEARCH_RESULT_COUNT=3"
      - "RAG_WEB_SEARCH_CONCURRENT_REQUESTS=10"
      - "SEARXNG_QUERY_URL=http://searxng:8080/search?q=<query>"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "./open-webui:/app/backend/data"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.open-webui.entrypoints=https"
      - "traefik.http.routers.open-webui.tls=true"
      - "traefik.http.routers.open-webui.middlewares=default-headers@file"
      - "traefik.http.services.open-webui.loadbalancer.server.port=8080"
    depends_on:
      - "ollama"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  searxng:
    container_name: "searxng"
    image: "searxng/searxng:latest"
    hostname: "searxng"
    networks:
      - "proxy"
    restart: "unless-stopped"
    environment:
      - "PUID=${PUID:-1000}"
      - "PGID=${PGID:-1000}"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "./searxng:/etc/searxng:rw"
    depends_on:
      - "ollama"
      - "open-webui"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.searxng.entrypoints=https"
      - "traefik.http.routers.searxng.tls=true"
      - "traefik.http.routers.open-webui.middlewares=default-headers@file"
      - "traefik.http.services.searxng.loadbalancer.server.port=8080"

networks:
  proxy:
    external: true