networks:
  caddy:
    external: true
  dns:
    external: true
  ollama:
    external: true

volumes:
  open-webui-data:
  ollama-data:
  whisper-data:

services:
  ollama:
    image: "${OLLAMA_IMAGE}"
    container_name: ollama
    dns:
      - 172.26.0.6
    environment:
      - "NODE_TLS_REJECT_UNAUTHORIZED=${NODE_TLS_REJECT_UNAUTHORIZED:-0}"
      - "OLLAMA_KEEP_ALIVE=${OLLAMA_KEEP_ALIVE:-24h}"
      - "PUID=${PUID:-1000}"
      - "PGID=${PGID:-1000}"
    extends:
      file: "../extends/hwaccel.ml.yml"
      service: "cpu" # set to one of [armnn, cuda, openvino, openvino-wsl]
    healthcheck:
      test: ["CMD", "ollama", "--version"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 30s
    hostname: ollama
    networks:
      - caddy
      - dns
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ollama-data:/root/.ollama

#  searxng:
#    image: "${SEARXNG_IMAGE}"
#    container_name: "searxng"
#    depends_on:
#      - "ollama"
#    environment:
#      - "PUID=${PUID:-1000}"
#      - "PGID=${PGID:-1000}"
#    hostname: "searxng"
#    networks:
#      - caddy
#    restart: "unless-stopped"
#    volumes:
#      - "/etc/localtime:/etc/localtime:ro"
#      - "/etc/timezone:/etc/timezone:ro"
#      - "./searxng:/etc/searxng:rw"
#
#  translate:
#    image: "${TRANSLATE_IMAGE}"
#    container_name: "libretranslate"
#    environment:
#      - "PUID=${PUID:-1000}"
#      - "PGID=${PGID:-1000}"
#      - "LT_DISABLE_WEB_UI=${LT_DISABLE_WEB_UI:-True}"
#      - "LT_LOAD_ONLY=${LT_LOAD_ONLY:-en,sk}"
#      - "LT_UPDATE_MODELS=${LT_UPDATE_MODELS:-True}"
#    extends:
#      file: "../extends/hwaccel.ml.yml"
#      service: "cpu" # set to one of [armnn, cuda, openvino, openvino-wsl]
#    hostname: "libretranslate"
#    restart: "unless-stopped"
#    volumes:
#      - "/etc/localtime:/etc/localtime:ro"
#      - "/etc/timezone:/etc/timezone:ro"
#      - "./whisper/libretranslate/data:/home/libretranslate/.local/share"
#      - "./whisper/libretranslate/cache:/home/libretranslate/.local/cache"