services:
  pihole:
    container_name: pihole
    depends_on:
      - unbound
    environment:
      # Set the appropriate timezone for your location from
      # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones, e.g:
      TZ: Europe/Bratislava
      # Set a password to access the web interface. Not setting one will result in a random password being assigned
      FTLCONF_webserver_api_password: 'correct horse battery staple'
      # If using Docker's default `bridge` network setting the dns listening mode should be set to 'ALL'
      FTLCONF_dns_listeningMode: ALL
      FTLCONF_dns_upstreams: 'unbound#5335'
    hostname: pihole
    image: pihole/pihole:latest
    networks:
      - caddy
      - dns_network
    restart: unless-stopped
    #ports:
      # Uncomment the below if using Pi-hole as your DHCP Server
      #- 67:67/udp
      # Uncomment the line below if you are using Pi-hole as your NTP server
      #- 123:123/udp
    volumes:
      - ./pihole:/etc/pihole
      - ./dnsmasq:/etc/dnsmasq.d
    cap_add:
      # See https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
      # Required if you are using Pi-hole as your DHCP server, else not needed
      - NET_ADMIN
      # Required if you are using Pi-hole as your NTP client to be able to set the host's system time
      - SYS_TIME
      # Optional, if Pi-hole should get some more processing time
      - SYS_NICE

  unbound:
    container_name: unbound
    image: klutchell/unbound:latest
    networks:
      - dns_network
    restart: unless-stopped
    volumes:
      - ./unbound:/etc/unbound/custom.conf.d

networks:
  caddy:
    external: true
  dns_network:
    driver: bridge