networks:
  caddy:
    external: true
  dns:
    driver: bridge

services:
  pihole:
    cap_add:
      # See https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
      # Required if you are using Pi-hole as your DHCP server, else not needed
      - NET_ADMIN
      # Required if you are using Pi-hole as your NTP client to be able to set the host's system time
      - SYS_TIME
      # Optional, if Pi-hole should get some more processing time
      - SYS_NICE
    container_name: pihole
    depends_on:
      - unbound
    environment:
      # Set the appropriate timezone for your location from
      # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones, e.g:
      TZ: Europe/Bratislava
      # Set a password to access the web interface. Not setting one will result in a random password being assigned
      FTLCONF_webserver_api_password: 'correct horse battery staple'
      # If using Docker's default `bridge` network setting the dns listening mode should be set to 'ALL'
      FTLCONF_dns_listeningMode: ALL
      FTLCONF_dns_upstreams: 'unbound#5335'
    hostname: pihole
    image: pihole/pihole:latest
    networks:
      - dns
      - caddy
    #ports:
      # DNS Ports
      #- "53:53/tcp"
      #- "53:53/udp"
      # Uncomment the below if using Pi-hole as your DHCP Server
      #- 67:67/udp
      # Uncomment the line below if you are using Pi-hole as your NTP server
      #- 123:123/udp
    restart: unless-stopped
    volumes:
      # For persisting Pi-hole's databases and common configuration file
      - ./pihole:/etc/pihole
      # Uncomment the below if you have custom dnsmasq config files that you want to persist. Not needed for most starting fresh with Pi-hole v6. If you're upgrading from v5 you and have used this directory before, you should keep it enabled for the first v6 container start to allow for a complete migration. It can be removed afterwards. Needs environment variable FTLCONF_misc_etc_dnsmasq_d: 'true'
      - ./dnsmasq:/etc/dnsmasq.d

  unbound:
    container_name: unbound
    image: klutchell/unbound:latest
    networks:
      - dns
    restart: unless-stopped
    volumes:
      - ./unbound:/etc/unbound/custom.conf.d
