services:
  tilde:
    container_name: "tilde"
    image: "nginx:latest"
    hostname: "tilde"
    networks:
      - "proxy"
    restart: "unless-stopped"
    volumes:
      - "./web:/usr/share/nginx/html:ro"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.tilde.entrypoints=https"
      - "traefik.http.routers.tilde.tls=true"
      - "traefik.http.services.tilde.loadbalancer.server.port=80"
      - "traefik.http.services.tilde.loadbalancer.server.scheme=http"

networks:
  proxy:
    external: true