networks:
  traefik:
    external: true

services:
  home-assistant:
    container_name: "home-assistant"
    image: "ghcr.io/home-assistant/home-assistant:stable"
    hostname: "home-assistant"
    network_mode: host
    networks:
      - "traefik"
    privileged: true
    restart: "unless-stopped"
    volumes:
      - .config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    labels:
      # Enable Traefik for this container
      - "traefik.enable=true"
      # Use the secure entry point
      - "traefik.http.routers.home-assistant.entrypoints=https"
      # Enable TLS on this router
      - "traefik.http.routers.home-assistant.tls=true"
      # Define the internal container port for routing
      - "traefik.http.services.home-assistant.loadbalancer.server.port=8123"
      - "traefik.http.services.home-assistant.loadbalancer.server.scheme=http"
      # Specify which Docker network Traefik should use for routing
      - "traefik.docker.network=traefik"