x-comfyui: &comfyui
    image: "pmikus/stable-diffusion:comfy-ui-0.0.1-cuda12.4.1"
    platform: "linux/amd64"
    build:
      context: .
      dockerfile: "Dockerfile"
      args:
        RELEASE: "0.0.1"
        BASE_IMAGE: "pmikus/ai-base:0.0.1-cuda12.4.1"
        CU_VERSION: "cu118"
        TORCH_VERSION: "2.3.0cu118"
        XFORMERS_VERSION: "0.0.26.post1"

    # Create a .env file in the same directory as this docker-compose.yml file
    # and populate it with environment variables. See .env.sample
    env_file:
      - ".env"

    # variables without a default will automatically inherit from the host environment
    environment:
      - "COMFYUI_FLAGS=${COMFYUI_FLAGS:-}"
      - "COMFYUI_PORT_HOST=${COMFYUI_PORT_HOST:-3000}"
      - "COMFYUI_METRICS_PORT=${COMFYUI_METRICS_PORT:-33000}"
      - "COMFYUI_URL=${COMFYUI_URL:-}"
      - "SSH_PORT_HOST=${SSH_PORT_HOST:-2222}"
    ports:
      # SSH available on host machine port 2222 to avoid conflict. Change to suit
      - "${SSH_PORT_HOST:-2222}:22"
      # ComfyUI web interface
      - "${COMFYUI_PORT_HOST:-3000}:${COMFYUI_PORT_HOST:-3000}"
      - "${COMFYUI_NGINX_PORT_HOST:-3001}:${COMFYUI_NGINX_PORT_HOST:-3001}"
    volumes:
      - type: "bind"
        source: "${HOST_COMFYUI_ROOT:-${COMFYUI_ROOT:-/glacier/ai/models/}}"
        target: "${CONTAINER_COMFYUI_ROOT:-/workspace/ComfyUI/models/}"
        bind:
          create_host_path: true
    tty: true
    stdin_open: true

services:
  comfyui-nvidia:
    <<: *comfyui
    privileged: true
    dns: 1.1.1.1
    deploy:
      resources:
        reservations:
          devices:
            - driver: "nvidia"
              count: 1
              capabilities: ["gpu"]

  #  comfyui-cpu:
  #  <<: *comfyui
  #  profiles:
  #   - "cpu"
