services:
  jellyfin:
    image: "jellyfin/jellyfin"
    container_name: "jellyfin"
    hostname: "jellyfin"
    restart: "unless-stopped"
    networks:
      - "proxy"
    volumes:
      - "./config:/config"
      - "./cache:/cache"
      - type: "bind"
        source: "./"
        target: "/media"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.jellyfin.tls=true"
      - "traefik.http.services.jellyfin.loadbalancer.server.scheme=http"

networks:
  proxy:
    external: true