- name: News
  width: slim
  center-vertically: true
  columns:
    - size: full
      widgets:
        - type: group
          widgets:
            - type: reddit
              subreddit: arduino
              show-thumbnails: true
            - type: reddit
              subreddit: selfhosted
              show-thumbnails: true
            - type: reddit
              subreddit: esp32
              show-thumbnails: true
            - type: reddit
              subreddit: fujifilm
              show-thumbnails: true
            - type: reddit
              subreddit: streetphotography
              show-thumbnails: true

        - type: rss
          style: vertical-list
          collapse-after: 3
          cache: 5m
          feeds:
            - url: http://rsshub:1200/telegram/channel/cz24news
              title: cz24news

        - type: videos
          style: grid-cards
          channels:
            - UCR-DXc1voovS8nhAvccRZhg # Jeff Geerling
            - UCajiMK_CY9icRhLepS8_3ug # Alex Ziskind
            - UC9Rrud-8CaHokDtK9FszvRg # Github Awesome
            - UCWQaM7SpSECp9FELz-cHzuQ # Dreams of Code
            - UCbY9xX3_jW5c2fjlZVBI4cg # TheAIGRID