networks:
  minio:
  proxy:
    external: true

volumes:
  minio-data:

services:
  minio:
    image: minio/minio:latest
    command: "server --console-address :9001"
    container_name: "minio"
    hostname: "minio"
    networks:
      - "proxy"
      - "minio"
    #ports:
    #  - "9001:9001"
    restart: "unless-stopped"
    volumes:
      - minio-data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.services.minio.loadbalancer.server.port=9000"
      - "traefik.http.routers.minio-console.tls=true"
      - "traefik.http.routers.minio-console.service=minio-console"
      - "traefik.http.routers.minio-console.rule=Host(`minio-console.localhost`)"
      - "traefik.http.services.minio-console.loadbalancer.server.port=9001"
      - "traefik.http.services.minio-console.loadbalancer.server.scheme=http"