services:
  metube:
    image: "ghcr.io/alexta69/metube"
    container_name: "metube"
    hostname: "metube"
    restart: "unless-stopped"
    networks:
      - "proxy"
    volumes:
      - "${HOME}/downloads:/downloads"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.metube.entrypoints=https"
      - "traefik.http.routers.metube.tls=true"
      - "traefik.http.services.metube.loadbalancer.server.port=8081"
      - "traefik.http.services.metube.loadbalancer.server.scheme=http"

networks:
  proxy:
    external: true