---
name: "Dev Containers Actions"

"on":
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  pull_request:
    branches:
      - "master"
  push:
    branches:
      - "master"

jobs:
  # Build image.
  build:
    runs-on: "ubuntu-latest"
    permissions:
      packages: "write"
      contents: "read"
    strategy:
      max-parallel: 1
      matrix:
        image:
          #- "ai-base"
          - "stable-diffusion-comfyui"
          #- "invokeai"
    steps:
      - name: Delete huge unnecessary tools folder
        run: "rm -rf /opt/hostedtoolcache"

      - name: "Check out the codebase."
        uses: "actions/checkout@v4"

      - name: "Cache Docker layers"
        id: actions_cache
        uses: "actions/cache@v3"
        with:
          path: "/tmp/.buildx-cache"
          key: "${{ runner.os }}-buildx-${{ github.sha }}"
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: "Set up Docker Buildx"
        id: "docker_buildx"
        uses: "docker/setup-buildx-action@v3"

      - name: "Login to DockerHub"
        id: "docker_login"
        uses: "docker/login-action@v3"
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: "Build Docker image"
        id: "docker_build"
        uses: "docker/bake-action@v4"
        if: github.event_name == 'pull_request'
        with:
          builder: "${{ steps.docker_buildx.outputs.name }}"
          push: false
          workdir: "${{ matrix.image }}/."

      - name: "Push Docker image"
        id: "docker_build_push"
        uses: "docker/bake-action@v4"
        if: github.event_name == 'push'
        with:
          builder: "${{ steps.docker_buildx.outputs.name }}"
          push: true
          workdir: "${{ matrix.image }}/."
