---
name: "Dev Containers Actions"

"on":
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  pull_request:
    branches: ["**"]
  push:
    tags: ["*"]
    branches:
      - "master"
env:
  # Hostname of your registry
  REGISTRY: "docker.io"
  SHA: ${{ github.event.pull_request.head.sha || github.event.after }}

jobs:
  # Build image.
  build:
    runs-on: "ubuntu-latest"
    permissions:
      packages: "write"
      contents: "read"
    strategy:
      max-parallel: 1
      matrix:
        image:
          - "ai-base"
          - "stable-diffusion-comfyui"
    steps:
      - name: "Delete huge unnecessary tools folder"
        run: "rm -rf /opt/hostedtoolcache"

      - name: "Checkout repository."
        uses: "actions/checkout@v4"

      - name: "Cache Docker layers"
        id: actions_cache
        uses: "actions/cache@v3"
        with:
          path: "/tmp/.buildx-cache"
          key: "${{ runner.os }}-buildx-${{ github.sha }}"
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: "Set up Docker Buildx"
        id: "docker_buildx"
        uses: "docker/setup-buildx-action@v3"

      # Authenticate to the container registry
      - name: "Authenticate to registry ${{ env.REGISTRY }}"
        id: "docker_login"
        uses: "docker/login-action@v3"
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and push Docker image with Buildx
      # (don't push on PR, load instead)
      - name: "Build and push Docker image"
        id: "docker_build"
        uses: "docker/bake-action@v4"
        if: github.event_name == 'pull_request'
        with:
          builder: "${{ steps.docker_buildx.outputs.name }}"
          sbom: ${{ github.event_name != 'pull_request' }}
          provenance: ${{ github.event_name != 'pull_request' }}
          push: ${{ github.event_name != 'pull_request' }}
          load: ${{ github.event_name == 'pull_request' }}
          workdir: "${{ matrix.image }}/."
          cache-from: type=gha
          cache-to: type=gha,mode=max
